#!/bin/bash

branch=`git symbolic-ref HEAD`
if [ "$branch" = "refs/heads/master" ]; then
    echo "Direct commits to the branch master are not allowed"
    exit 1
fi

npm run precommit

RESULT=$?
[ $RESULT -ne 0 ] && exit 1
exit 0
