image: node:8

before_script:
  - npm install -y

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
    - node_modules/

test:
  only:
    - develop
  script:
    - npm run test

build:
  only:
    - master
  variables:
    CHANNEL: "update"

  script:
    - export IMG_VERSION=`cat package.json |grep version|cut -d ':' -f 2| sed 's/[" ,]//g'`
    - export PN_DATA="{\"BuildId\":\"$CI_BUILD_ID\",\"ProjectId\":\"$CI_PROJECT_ID\",\"AppVersion\":\"$IMG_VERSION\" }"
    - export PAYLOAD=`echo -e "import urllib; print(urllib.quote('$PN_DATA'))" | python`
    - npm run test
    - npm run build
    - tar czf release.tar.gz package.json pm2.config.json update.sh dist/

  after_script:
    - curl https://ps.pndsn.com/publish/$PUB_KEY/$SUB_KEY/0/$CHANNEL/cb/$PAYLOAD

  artifacts:
    paths:
      - release.tar.gz
