image: node:8

before_script:
  - npm install -y

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
    - node_modules/

test:
  only:
    - develop
  script:
    - npm run test

build:
  only:
    - master
  script:
    - export IMG_VERSION=`cat package.json |grep version|cut -d ':' -f 2| sed 's/[" ,]//g'`
    - npm run test
    - npm run build
    - tar czf release.tgz package.json dist/
    - export PAYLOAD=`python -c "exec(\"import urllib; print(urllib.quote('{{ "BuildId": {0}, "ProjectId": {1}, "AppVersion": {2} }}'.format($CI_BUILD_ID, $CI_PROJECT_ID, $IMG_VERSION)))\")"`
    - curl https://ps.pndsn.com/publish/$PUB_KEY/$SUB_KEY/0/$CHANNEL/cb/$PAYLOAD

  artifacts:
    paths:
      - release.tgz
