image: node:6

before_script:
  - npm install -y

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
    - node_modules/


test:
  only:
    - develop
  scripts:
    - npm run test

build:
  only:
    - master
  script:
    - export IMG_VERSION=`cat package.json |grep version|cut -d ':' -f 2| sed 's/[" ,]//g'`
    - npm run test
    - npm run build
    - tar czf dist.tgz dist/

   artifacts:
      paths:
      - dist.tgz
