image: node:8

before_script:
  - npm install -y

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
    - node_modules/

test:
  only:
    - develop
  script:
    - npm run test

build:
  only:
    - master
  variables:
    CHANNEL: "update"

  script:
    - npm run test
    - npm run build
    - tar czf release.tar.gz package.json pm2.config.json update.sh s6-update-init dist/

  after_script:
    - export IMG_VERSION=`cat package.json |grep version|cut -d ':' -f 2| sed 's/[" ,]//g'`
    - export PN_DATA="{\"BuildId\":\"$CI_BUILD_ID\",\"ProjectId\":\"$CI_PROJECT_ID\",\"AppVersion\":\"$IMG_VERSION\" }"
    - export PAYLOAD=`node -e "console.log(encodeURIComponent('$PN_DATA'))"`
    - echo "RUN PubNub notification $PAYLOAD"
    - curl --silent https://ps.pndsn.com/publish/$PUB_KEY/$SUB_KEY/0/$CHANNEL/cb/$PAYLOAD

  artifacts:
    paths:
      - release.tar.gz
